name: Testing

# Controls when the workflow will run
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    container:
      image: mcr.microsoft.com/dotnet/sdk:5.0

    steps:
      - uses: actions/checkout@v2
                  
      - name: Restore dependencies
        run: |
          dotnet --version
          echo this is running on - $RUNNER_OS
          dotnet restore
          dotnet build --configuration 'release'

      - name: run app
        run: http://localhost
          