name: Testing

# Controls when the workflow will run
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    container:
      image: mcr.microsoft.com/dotnet/sdk:5.0

    services:
          sqlserver:
            image: mcr.microsoft.com/mssql/server:2019-latest
            env:
              SA_PASSWORD: P@ssword1$
              ACCEPT_EULA: Y
            ports:
              - "1433:1433"

    steps:
      - uses: actions/checkout@v2
                  
      - name: Restore dependencies
        run: |
          dotnet --version
          echo this is running on - $RUNNER_OS
          dotnet restore
          dotnet build --configuration 'release'

      - name: connect to sql server
        run: |
          sudo docker exec -it sqlserver "bash"
          /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P P@ssword1$
          CREATE DATABASE TestDB
          SELECT Name from sys.Databases
          GO


          